---

language: 'python'
python: '2.7'

virtualenv:
  system_site_packages: true

before_install: True
install: True

script:
  #- 'git clone --depth 1 https://github.com/nickjj/rolespec'
  #- 'cd rolespec ; bin/rolespec -r https://github.com/drybjed/test-suite'
  - 'sudo apt-get -y install libcap2-bin'
  - 'sudo capsh --print'
  - 'sudo getcap $(readlink -f /sbin/iptables)'
  - 'echo "Separate branch test"'

